---
title: "Miami Prediction"
author: "Anna Duan"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
####load libraries, etc
library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(stargazer)
library(mapview)
library(osmdata)
library(tidycensus)
library(tidygeocoder)
library(raster)
library(rnaturalearth)
library(RColorBrewer)
library(rnaturalearthdata)
library(geosphere)

mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

palette5 <- c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")

qBr <- function(df, variable, rnd) {
  if (missing(rnd)) {
    as.character(quantile(round(df[[variable]],0),
                          c(.01,.2,.4,.6,.8), na.rm=T))
  } else if (rnd == FALSE | rnd == F) {
    as.character(formatC(quantile(df[[variable]]), digits = 3),
                 c(.01,.2,.4,.6,.8), na.rm=T)
  }
}

q5 <- function(variable) {as.factor(ntile(variable, 5))}

#nearest neighbor function 
nn_function <- function(measureFrom,measureTo,k) {
  measureFrom_Matrix <- as.matrix(measureFrom)
  measureTo_Matrix <- as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
  output <-
    as.data.frame(nn) %>%
    rownames_to_column(var = "thisPoint") %>%
    gather(points, point_distance, V1:ncol(.)) %>%
    arrange(as.numeric(thisPoint)) %>%
    group_by(thisPoint) %>%
    summarize(pointDistance = mean(point_distance)) %>%
    arrange(as.numeric(thisPoint)) %>% 
    dplyr::select(-thisPoint) %>%
    pull()
  
  return(output)  
}
```


```{r download data}
#projected to NAD 1983 StatePlane Florida East FIPS 0901 Feet



#STUDY AREA
miamiBound <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Municipal_Boundary.geojson") %>%
  filter(NAME == "MIAMI BEACH" | NAME == "MIAMI") %>%
  st_union() %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658')



#STUDY AREA OSM (not projected so that it works)
miamiBoundOSM <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Municipal_Boundary.geojson") %>%
  filter(NAME == "MIAMI BEACH" | NAME == "MIAMI") %>%
  st_union()



#HOUSE DATA
houses <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/studentsData.geojson") %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658')



#HOUSE DATA OSM (Not projected)
housesOSM <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/studentsData.geojson")



#CENSUS
census_api_key("d9ebfd04caa0138647fbacd94c657cdecbf705e9", install = TRUE, overwrite = TRUE)
#read in: vacant property, total housing units, mhhinc, white, population, owner occ, renter occ, travel time to work
acs <- 
  get_acs(geography = "tract", variables = c("B25002_003E", "B25001_001E", "B19013_001E", "B01001A_001E", "B01003_001E", "B07013_002E", "B07013_003E", "B08012_001E"), year=2018, state=12, county=086, geometry=T) %>% 
  st_transform('ESRI:102658')
#filter for Miami/Miami beach tracts
acs <- 
  rbind(
    st_centroid(acs)[miamiBound,] %>%
      st_drop_geometry() %>%
      left_join(acs) %>%
      st_sf() %>%
      mutate(inMiami = "YES"),
    st_centroid(acs)[miamiBound, op = st_disjoint] %>%
      st_drop_geometry() %>%
      left_join(acs) %>%
      st_sf() %>%
      mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES") %>%
  dplyr::select(-inMiami)
#long to wide form
acs <- 
  acs %>%
  dplyr::select(-moe, -GEOID) %>%
  spread(variable, estimate) %>%
  dplyr::select(-geometry) %>%
  rename(vacantUnits = B25002_003, 
         totalUnits = B25001_001,
         medHHInc = B19013_001,
         white = B01001A_001, 
         population = B01003_001,
         ownerOcc = B07013_002, 
         renterOcc = B07013_003,
         timeToWork = B08012_001)
#mutate
acs <- 
  acs %>%
  mutate(pctVacant = ifelse(totalUnits > 0, vacantUnits / totalUnits, 0),
         pctWhite = ifelse(population > 0, white / population, 0),
         totalOcc = ownerOcc + renterOcc,
         pctRenterOcc = ifelse(totalOcc > 0, renterOcc / totalOcc, 0),
         year = "2018") %>%
  dplyr::select(-totalUnits,-vacantUnits,-totalUnits,-population,-white, -ownerOcc, -renterOcc, -totalOcc)
  

#OSM BBOX (uses the non-projected base)
xmin = st_bbox(miamiBoundOSM)[[1]]
ymin = st_bbox(miamiBoundOSM)[[2]]
xmax = st_bbox(miamiBoundOSM)[[3]]  
ymax = st_bbox(miamiBoundOSM)[[4]]



#FOOD AND BEVERAGE SPOTS
 foodBev <- opq(bbox = c(xmin, ymin, xmax, ymax)) %>% 
  add_osm_feature(key = 'amenity', value = c("bar","pub","restaurant","cafe")) %>%
   osmdata_xml(filename = 'foodBev.osm')
 #project
 foodBev <- sf::st_read('foodBev.osm', layer = 'points') %>%
     st_as_sf(coords = c("LON", "LAT"), crs = EPSG:3857, agr = "constant") %>%
  st_transform('ESRI:102658')
 #filter
 foodBev <- rbind(
    st_centroid(foodBev)[miamiBound,] %>%
      st_drop_geometry() %>%
      left_join(foodBev) %>%
      st_sf() %>%
      mutate(inMiami = "YES"),
    foodBev[miamiBound, op = st_disjoint] %>%
      st_drop_geometry() %>%
      left_join(foodBev) %>%
      st_sf() %>%
      mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES") %>%
   dplyr::select(name)
 
 
 
#COASTLINE
Coastline<-opq(bbox = c(xmin, ymin, xmax, ymax)) %>% 
  add_osm_feature("natural", "coastline") %>%
  osmdata_sf()
#add to housesOSM and convert to miles, then add to houses
housesOSM <-
  housesOSM %>%  
  mutate(CoastDist=(geosphere::dist2Line(p=st_coordinates(st_centroid(housesOSM)),
                                        line=st_coordinates(Coastline$osm_lines)[,1:2])*0.00062137)[,1])
houses <-
  houses %>%
  mutate(distWater = housesOSM$CoastDist)

#green space
#green <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/green.geojson") %>%
#  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
#  st_transform('ESRI:102658')
#green <- rbind(
#    st_centroid(green)[miamiBound,] %>%
#      st_drop_geometry() %>%
#      left_join(green) %>%
#      st_sf() %>%
#      mutate(inMiami = "YES"),
#    green[miamiBound, op = st_disjoint] %>%
#      st_drop_geometry() %>%
#      left_join(green) %>%
#      st_sf() %>%
#      mutate(inMiami = "NO")) %>%
#  filter(inMiami == "YES") %>%
#  mutate(counter = 1)



#PARKS
muniParks <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Municipal_Park_Boundary.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') %>%
  dplyr::select(NAME, ADDRESS, CITY, CLASS, Shape__Area)
countyParks <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/County_Park_Boundary.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') %>%
    dplyr::select(NAME, ADDRESS, CITY, CLASS, Shape__Area)
parks <- bind_rows(muniParks, countyParks) %>% 
  filter(CITY == "Miami" | CITY == "Miami Beach") %>%
  mutate(counter = 1)



#SCHOOL DISTRICT
schoolDist <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/School_Board_District.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') %>%
  dplyr::select(ID) %>%
  mutate (ID = as.numeric(ID))



#PUBLIC SCHOOL CATCHMENT/ATTENDANCE ZONES
#elementary
elementary <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Elementary_School_Attendance_Boundary.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') 
elementary <- rbind(
  st_centroid(elementary)[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(elementary) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  st_centroid(elementary)[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(elementary) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES") %>%
  dplyr::select(NAME)
#middle
middle <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Middle_School_Attendance_Boundary.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658')
middle <- rbind(
  st_centroid(middle)[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(middle) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  st_centroid(middle)[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(middle) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES") %>%
  dplyr::select(NAME)
#high
high <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/High_School_Attendance_Boundary.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658')
high <- rbind(
  st_centroid(high)[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(high) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  st_centroid(high)[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(high) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES") %>%
  dplyr::select(NAME)



#crime?



#PUBLIC TRANSPORTATION
#bus
bus <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Bus_Stop.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant")  %>%
  st_transform('ESRI:102658')
bus <- rbind(
  bus[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(bus) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  bus[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(bus) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES")
#metro mover
metromover <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Metromover_Station.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') 
metromover <- rbind(
  metromover[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(metromover) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  metromover[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(metromover) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES")
#metro rail
metrorail <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Metrorail_Station.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') 
metrorail <- rbind(
  metrorail[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(metrorail) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  metrorail[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(metrorail) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES")



#CULTURE SPOTS
culture <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Culture_Venue.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') %>%
  filter(CITY == "Miami" | CITY == "Miami Beach")



#COMMERCIAL PROPERTIES
#read, project
commercial <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Commercial_Property.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') 
#filter
commercial <- rbind(
  commercial[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(commercial) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  commercial[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(commercial) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES")



#FLOOD RISK ZONES
#read, project
flood <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/FEMA\ FLOOD\ ZONE") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658') 
#filter
 flood <-
   rbind(
  st_centroid(flood)[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(flood) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  st_centroid(flood)[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(flood) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES") %>%
   dplyr::select(-inMiami, -SHAPE_Length, -ELEV, -FID) %>%
   dplyr::rename(FloodZone = FZONE, FloodHazard = ZONESUBTY)
 
 
 
#CONTAMINATED SITES
contaminated <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/Multi-Property_Contaminated_Site.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658')
 contaminated <-
   rbind(
  st_centroid(contaminated)[miamiBound,] %>%
    st_drop_geometry() %>%
    left_join(contaminated) %>%
    st_sf() %>%
    mutate(inMiami = "YES"),
  st_centroid(contaminated)[miamiBound, op = st_disjoint] %>%
    st_drop_geometry() %>%
    left_join(contaminated) %>%
    st_sf() %>%
    mutate(inMiami = "NO")) %>%
  filter(inMiami == "YES")
 
 
 
#OTHER VARIABLES
# landuse <- st_read("https://opendata.arcgis.com/datasets/8c6e2575c8ad46eb887e6bb35825e1a6_0.geojson") 
 #AD: this is for Philadelphia

utility_water <- st_read("https://opendata.arcgis.com/datasets/d22634dc2f4745de8a9d8fb72e2bce3a_0.geojson") 
 
utility_sewer <- st_read("https://opendata.arcgis.com/datasets/e4ac368322ee43c798ff194265e2a488_0.geojson")

employee_pay <- st_read("https://opendata.arcgis.com/datasets/4b372d5fa4884947a20d03464b292219_0.geojson")

low_income_depressed <- st_read("https://opendata.arcgis.com/datasets/40119bfc50274c1da548ec8022e9a7a9_0.geojson")

neighborhood_revitalization <- st_read("https://opendata.arcgis.com/datasets/fe6f419e21264158b18eb77be9870d97_0.geojson")

#shop <- st_read("E:/Upenn/CPLN508/miami/2_Miami-Prediction/Raw Data/shop_point.geojson")
shop <- st_read("/Users/annaduan/Documents/GitHub/2_Miami\ Prediction/Raw\ Data/shop_point.geojson") %>%
  st_as_sf(coords = c("LON", "LAT"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102658')

```


```{r wrangle, echo=FALSE}
 
#TOD
 metroRBuffer <- metrorail %>% 
     st_buffer(0.5*5280) %>% #in feet
   st_union() %>% 
   st_as_sf() %>% 
   mutate(TOD = 1)
#mark as TOD or not
 houses$TOD <- houses %>% 
   st_centroid() %>% 
   st_join(metroRBuffer) %>% 
   mutate(TOD = ifelse(is.na(TOD), 0, 1)) %>%
   pull(TOD)
 
 
 
 #CONTAMINATION BUFFER
 contaminatedBuffer <- contaminated %>%
   st_buffer(846) %>%
   st_union() %>%
   st_as_sf() %>%
   mutate(contam = 1)
 houses$contamination <- houses %>%
   st_centroid() %>%
   st_join(contaminatedBuffer) %>%
   mutate(contam = ifelse(is.na(contam), 0, 1)) %>%
   pull(contam)
 

 
#NEAREST NEIGHBOR (some are used for testing, to determine feature buffer distances)
 st_c <- st_coordinates
 houses <-
   houses %>% 
   mutate(
     #contaminated
     contaminatedNN1 = nn_function(st_c(st_centroid(houses)), st_c(st_centroid(commercial.sf)), 2),
     #commercial properties NN
     commNN1 = nn_function(st_c(st_centroid(houses)), st_c(st_centroid(commercial.sf)), 2),
     #parks
     parkNN1 = nn_function(st_c(st_centroid(houses)), st_c(st_centroid(parks)), 1),
     #metro mover stations
     metroMNN5 = nn_function(st_c(st_centroid(houses)), st_c(metromover), 5),
     #metro rail stations
     metroRNN1 = nn_function(st_c(st_centroid(houses)), st_c(metrorail), 1),
     #bus stations
     busNN1 = nn_function(st_c(st_centroid(houses)), st_c(bus), 1),
     #culture
     cultureNN1 = nn_function(st_c(st_centroid(houses)), st_c(bus), 1),
     #food/drinks
     foodBevNN1 = nn_function(st_c(st_centroid(houses)), st_c(foodBev), 1))

 
 
#COMMERCIAL BUFFER
 commercial <- commercial %>% 
   mutate(counter = 1) %>%
   dplyr::select(counter)
 #count properties within each buffer
houses$commercialProperties <-
   st_buffer(houses, 846) %>%
   aggregate(commercial, ., sum) %>% 
   st_drop_geometry() %>% 
   pull(counter)
 


#FOOD AND BEV BUFFER
 foodBev <- foodBev %>% 
   mutate(counter = 1) %>%
   dplyr::select(counter)
 #count parks within each buffer
houses$foodEstablishments <-
   st_buffer(houses, 2774) %>%
   aggregate(foodBev, ., sum) %>% 
   st_drop_geometry() %>% 
   pull(counter)



#CULTURE BUFFER
 culture <- culture %>% 
   mutate(counter = 1) %>%
   dplyr::select(counter)
 #count culture within each buffer
houses$cultureSpots <-
   st_buffer(houses, 774) %>%
   aggregate(culture, ., sum) %>% 
   st_drop_geometry() %>% 
   pull(counter)




#METRORAIL BUFFER
 metrorail <- metrorail %>% 
   mutate(counter = 1) %>%
   dplyr::select(counter)
 #count stops within each buffer
houses$metrorailStops <-
   st_buffer(houses, 12076.7) %>%
   aggregate(metrorail, ., sum) %>% 
   st_drop_geometry() %>% 
   pull(counter)



#METROMOVER BUFFER
 metromover <- metromover %>% 
   mutate(counter = 1) %>%
   dplyr::select(counter)
 #count metroM stops within each buffer
houses$metromoverStops <-
   st_buffer(houses, 18845) %>%
   aggregate(metromover, ., sum) %>% 
   st_drop_geometry() %>% 
   pull(counter)



#BUS BUFFER
 bus <- bus %>% 
   mutate(counter = 1) %>%
   dplyr::select(counter)
 #count bus within each buffer
houses$busStops <-
   st_buffer(houses, 775) %>%
   aggregate(bus, ., sum) %>% 
   st_drop_geometry() %>% 
   pull(counter)
 


 #PARKS BUFFER + AREA CALCULATION (using 1600ft buffer distance because the mean NN1 = 1600)
 #get centroids
 parkCentroids <- parks %>% 
   st_centroid(parks) %>%    #get centroids of park layer
  dplyr::select(counter)
 #count parks within each buffer
houses$parkCount <-
   st_buffer(houses, 1600) %>%
   aggregate(parkCentroids, ., sum) %>% 
   st_drop_geometry() %>% 
   pull(counter)
#make buffer for each house
parkBuffer <- st_buffer(houses, 1600) %>%
  dplyr::select(Property.Address) %>%
  st_as_sf()
#calculate area of park space in each buffer
bufferedParks <- st_intersection(parkBuffer, parks) %>%
  group_by(Property.Address) %>%
  summarise() %>%
  mutate(parkArea = units::drop_units(st_area(.))) %>%
  st_drop_geometry()
#add park area back to houses file
houses <-
  left_join(houses, bufferedParks)



#SCHOOL CATCHMENT CATEGORIES
 houses <-
   st_intersection(elementary, houses) %>%
   rename(elemCatch = NAME) %>%
   st_intersection(middle, houses) %>%
   rename(middleCatch = NAME) %>%
   st_intersection(high, houses) %>%
   rename(highCatch = NAME)
 

 
 #SCHOOL DISTRICT CATEGORIES
 houses <-
   st_intersection(schoolDist, houses) %>%
   rename(schoolDist = ID)
 
 
 
#ADD ACS DATA
 houses <- 
   st_intersection(acs, houses) %>%
   rename(censusTract = NAME)
 
 
 
#FLOOD RISK CATEGORIES
 houses <-
   st_intersection(flood, houses) %>%
   dplyr::select(-SHAPE_Area)
 
 
 
 #HOUSE AGE
 houses <-
   houses %>%
   mutate(age = ifelse(is.na(YearBuilt), 0, (2020 - YearBuilt)))
 
 
 
 #MAKE CATEGORICAL VARIABLES
 houses <- 
  houses %>%
  mutate(Bed.cat = case_when(
                  Bed >= 0 & Bed < 3  ~ "Up to 2 Beds",
                  Bed >= 3 & Bed < 4  ~ "3 Beds",
                  Bed > 4                    ~ "4+ Beds"))
 
```


```{r correlation}
 #split house set
 train <- filter(houses, SalePrice != 0)
 predict <- filter(houses, SalePrice == 0) 
 
 #####housing correlation
#1*bedrooms

#2bathrooms  

#3year built

#4sq ft

#5lot size

#6senior vs long term senior
 
#land? bldg?total?
 
 #cor test
 cor.test(houses$age, houses$SalePrice, method = "pearson")

 #reg1
 reg <- lm(SalePrice ~ ., data = st_drop_geometry(houses) %>% 
             dplyr::select(SalePrice, LivingSqFt, Bed.cat, Bath, LotSize, Stories, Zoning, YearBuilt, timeToWork, parkArea, medHHInc, pctVacant, contamination, foodEstablishments))
 summary(reg)
 
 #corr matrix
 numericVars <- 
   select_if(st_drop_geometry(houses), is.numeric) %>% na.omit()
 
 ggcorrplot(
   round(cor(numericVars), 1), 
   p.mat = cor_pmat(numericVars),
   colors = c("#25CB10", "white", "#FA7800"),
   type="lower",
   insig = "blank") +  
   labs(title = "Correlation across numeric variables") 
 
 
 
```

```{r testing figures}
####MAP: DEPENDENT VAR. (sale price)####
ggplot() +
  geom_sf(data = acs, colour = "white", fill = "gray") +
  geom_sf(data = train, aes(colour = q5(SalePrice)), 
          show.legend = "point", size = 0.7) +
  scale_colour_manual(values = palette5,
                      labels=qBr(train,"SalePrice"),
                      name="Quintile\nBreaks") +
  labs(title="Home Sale Price", subtitle="Miami, FL") +
  mapTheme()
```

```{r cross validation}
```

```{r final figures}
#distance to water
ggplot() +
  geom_sf(data = acs) +
  geom_sf(data = houses, aes(colour = distWater)) +
  mapTheme()

#park area
ggplot() + 
  geom_sf(data = houses, aes(colour = q5(parkArea))) +
  scale_fill_manual(values = palette5) +
  mapTheme()
```